Dataset

In [2]:
pip install faker

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 18.5 MB/s eta 0:00:00


In [3]:
import pandas as pd
import random
import faker
from datetime import datetime

In [4]:
# Initialize Faker to generate random data
fake = faker.Faker()

In [5]:
# List of email domains
email_domains = ['gmail.com', 'yahoo.com', 'outlook.com']

In [6]:
# Define sample lists for categorical data
location_types = ['Urban', 'Suburban', 'Rural']
cellphone_brands = ['Apple', 'Samsung', 'Huawei', 'Oppo', 'Vivo', 'Xiaomi']
digital_interests = ['Gaming', 'Fitness', 'Social Media', 'Music', 'Tech News', 'Shopping', 'Travel', 'Sport']

In [7]:
# Function to generate a sample user
def generate_user(user_id):
    location = fake.city()  # Random city from Faker's city generator (global cities)
    login_time = fake.date_time_this_year()  # Random login time this year
    name = fake.name()  # Random name
    # Create email with a random domain from the list
    email = f"{name.split()[0].lower()}.{name.split()[1].lower()}@{random.choice(email_domains)}"

    # Generate a phone number in the format XXX-XXXX (7 digits)
    phone_number = f"{random.randint(100, 999)}-{random.randint(1000, 9999)}"  # Format: 3 digits - 4 digits

    birth_year = random.randint(1980, 2005)  # Birth year explicitly limited to 1980-2005
    cellphone_brand = random.choice(cellphone_brands)  # Random cellphone brand
    digital_interest = random.choice(digital_interests)  # Random digital interest
    location_type = random.choice(location_types)  # Random location type (urban, suburban, rural)

    return {
        'User ID': user_id,
        'Location': location,
        'Login Time': login_time,
        'Name': name,
        'Email': email,
        'Phone Number': phone_number,
        'Birth Year': birth_year,
        'Cellphone Brand': cellphone_brand,
        'Digital Interest': digital_interest,
        'Location Type': location_type
    }

In [8]:
# Generate a sample dataset with 50 users
num_users = 1000
users_data = [generate_user(i) for i in range(1, num_users + 1)]

In [9]:
# Create a DataFrame
df = pd.DataFrame(users_data)

In [10]:
# Display the first 10 rows of the DataFrame
print(df.head(10))

   User ID         Location                 Login Time               Name  \
0        1      New Clayton 2024-08-31 18:29:54.343820        Adam Torres   
1        2         Cruzside 2024-05-14 09:12:53.319785     Robert Pearson   
2        3  Port Joshuaberg 2024-06-26 09:17:40.901776        Jeremy Lang   
3        4       Whitehaven 2024-03-13 02:25:55.418401         Sean Perez   
4        5      Kristenstad 2024-12-22 06:29:03.470873     Sabrina Farley   
5        6       Laurahaven 2024-05-21 13:57:56.478976     Courtney Walsh   
6        7     South Pamela 2024-07-26 01:51:09.395429     Jessica Gentry   
7        8   Port Ericabury 2024-12-23 19:36:29.010990       James Snyder   
8        9    South Jessica 2024-05-19 11:12:26.539876      Dale Jennings   
9       10  Port Stevenport 2024-07-24 16:50:46.706945  Benjamin Alvarado   

                         Email Phone Number  Birth Year Cellphone Brand  \
0        adam.torres@gmail.com     236-8054        1994          Huawei   
1 

In [ ]:
# Save dataset to CSV (optional)
df.to_csv('sample_device_user_2.csv', index=False)

Cleaning Data

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
df = pd.read_csv('sample_device_user_2.csv')

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   User ID           1000 non-null   int64 
 1   Location          1000 non-null   object
 2   Login Time        1000 non-null   object
 3   Name              1000 non-null   object
 4   Email             1000 non-null   object
 5   Phone Number      1000 non-null   object
 6   Birth Year        1000 non-null   int64 
 7   Cellphone Brand   1000 non-null   object
 8   Digital Interest  1000 non-null   object
 9   Location Type     1000 non-null   object
dtypes: int64(2), object(8)
memory usage: 78.2+ KB


In [40]:
df['Age'] = 2024 - df['Birth Year']

In [41]:
df['Login Time'] = pd.to_datetime(df['Login Time'])
df['Login Hour'] = df['Login Time'].dt.hour

In [42]:
# Generate Name
df['First Name'] = df['Name'].apply(lambda x: x.split()[0])
df['Last Name'] = df['Name'].apply(lambda x: x.split()[1])

In [43]:
# Generate Email
df['Email Username'] = df['Email'].apply(lambda x: x.split('@')[0])
df['Email Domain'] = df['Email'].apply(lambda x: x.split('@')[1])

In [44]:
# Generate Phone Number
df['Area Code'] = df['Phone Number'].apply(lambda x: x.split('-')[0])
df['Local Number'] = df['Phone Number'].apply(lambda x: x.split('-')[1])

In [45]:
# Generate Login Time
df['Login Date'] = df['Login Time'].dt.date

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   User ID           1000 non-null   int64         
 1   Location          1000 non-null   object        
 2   Login Time        1000 non-null   datetime64[ns]
 3   Name              1000 non-null   object        
 4   Email             1000 non-null   object        
 5   Phone Number      1000 non-null   object        
 6   Birth Year        1000 non-null   int64         
 7   Cellphone Brand   1000 non-null   object        
 8   Digital Interest  1000 non-null   object        
 9   Location Type     1000 non-null   object        
 10  Age               1000 non-null   int64         
 11  Login Hour        1000 non-null   int32         
 12  First Name        1000 non-null   object        
 13  Last Name         1000 non-null   object        
 14  Email Username    1000 no

Exploratory Data Analysis

In [49]:
pip install spicy

In [50]:
from spicy import stats

In [51]:
# Define Confidence Interval
def confidence_interval_mean(data, confidence=0.95):
    n = len(data)
    mean = np.mean(data)
    std_err = np.std(data, ddof=1) / np.sqrt(n)
    h = std_err * stats.t.ppf((1 + confidence) / 2., n-1)
    return mean - h, mean + h

In [53]:
# Confidence Interval of Age, Birth Year, and Login Hour
age_lower, age_upper = confidence_interval_mean(df['Age'], confidence=0.95)
birthyear_lower, birthyear_upper = confidence_interval_mean(df['Birth Year'], confidence=0.95)
loginhour_lower, loginhour_upper = confidence_interval_mean(df['Login Hour'], confidence=0.95)

print(f"95% Confidence Interval for Age: ({age_lower:.2f}, {age_upper:.2f})")
print(f"95% Confidence Interval for Birth Year: ({birthyear_lower:.2f}, {birthyear_upper:.2f})")
print(f"95% Confidence Interval for Login Hour: ({loginhour_lower:.2f}, {loginhour_upper:.2f})")

95% Confidence Interval for Age: (30.95, 31.91)
95% Confidence Interval for Birth Year: (1992.09, 1993.05)
95% Confidence Interval for Login Hour: (11.23, 12.10)


In [34]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [54]:
df.drop(['Name','User ID', 'Location', 'Login Time', 'Email', 'Phone Number', 'Birth Year', 'First Name', 'Last Name',
        'Email Username', 'Area Code', 'Local Number', 'Login Date'], axis=1, inplace=True)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Cellphone Brand   1000 non-null   object
 1   Digital Interest  1000 non-null   object
 2   Location Type     1000 non-null   object
 3   Age               1000 non-null   int64 
 4   Login Hour        1000 non-null   int32 
 5   Email Domain      1000 non-null   object
dtypes: int32(1), int64(1), object(4)
memory usage: 43.1+ KB


In [56]:
X = pd.get_dummies(df, columns=['Cellphone Brand', 'Digital Interest', 'Email Domain']).drop('Location Type', axis=1)

In [57]:
y = df['Location Type']
ordinal_encoder = OrdinalEncoder(categories=[['Rural', 'Suburban', 'Urban']])
y = ordinal_encoder.fit_transform(y.values.reshape(-1, 1))


In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [60]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 19), (200, 19), (800, 1), (200, 1))

Logistic Regression

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error

In [62]:
LR = LogisticRegression()

In [63]:
LR.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [64]:
LR.score(X_train, y_train)

0.40125

In [65]:
print('Coef : ', LR.coef_)
print('Intercept : ', LR.intercept_)

Coef :  [[ 6.90283082e-03  1.00708679e-04  5.03659858e-02 -6.65259390e-02
  -6.48589094e-02 -6.76759075e-02 -4.10579691e-02  7.47721745e-02
  -5.27431643e-02 -1.98425091e-01 -1.38669242e-01  9.88308782e-02
   4.71910475e-02  5.12556276e-02  1.54187914e-02  6.21605883e-02
   7.65870334e-02 -1.03899071e-01 -8.76685272e-02]
 [-5.45373805e-03 -1.41819573e-02  5.91021188e-02 -3.45886360e-02
   1.35923504e-01  1.06823206e-01  3.53041422e-02 -9.40991538e-02
  -1.60544619e-01  2.44414978e-01  1.44594265e-03  1.20861821e-01
  -1.32532697e-01  3.07818828e-01 -3.60728147e-02 -1.36926259e-01
   4.41485583e-02  3.57553455e-02  1.28561277e-01]
 [-1.44909277e-03  1.40812486e-02 -1.09468105e-01  1.01114575e-01
  -7.10645943e-02 -3.91472985e-02  5.75382694e-03  1.93269792e-02
   2.13287783e-01 -4.59898868e-02  1.37223299e-01 -2.19692699e-01
   8.53416494e-02 -3.59074456e-01  2.06540233e-02  7.47656703e-02
  -1.20735592e-01  6.81437255e-02 -4.08927499e-02]]
Intercept :  [-0.12466047  0.22595597 -0.10129

In [66]:
# Predicted Values
y_pred_LR1 = LR.predict(X_train)
y_pred_LR2 = LR.predict(X_test)

In [67]:
LR.score(X_test, y_test)

0.345

In [68]:
print('Training Data')
print('MAE : ', mean_absolute_error(y_train, y_pred_LR1))
print('MSE : ', mean_squared_error(y_train, y_pred_LR1))
print('RMSE : ', root_mean_squared_error(y_train, y_pred_LR1))

Training Data
MAE :  0.79875
MSE :  1.19875
RMSE :  1.0948744220229094


In [69]:
print('Testing Data')
print('MAE : ', mean_absolute_error(y_test, y_pred_LR2))
print('MSE : ', mean_squared_error(y_test, y_pred_LR2))
print('RMSE : ', root_mean_squared_error(y_test, y_pred_LR2))

Testing Data
MAE :  0.855
MSE :  1.255
RMSE :  1.120267825120404


In [70]:
print('Training Data')
print('Accuracy : ', accuracy_score(y_train, y_pred_LR1))
print('\nConfusion Matrix : \n', confusion_matrix(y_train, y_pred_LR1))
print('\nClassification Report : \n',classification_report(y_train, y_pred_LR1))

Training Data
Accuracy :  0.40125

Confusion Matrix : 
 [[ 88  99  84]
 [ 68 129  75]
 [ 76  77 104]]

Classification Report : 
               precision    recall  f1-score   support

         0.0       0.38      0.32      0.35       271
         1.0       0.42      0.47      0.45       272
         2.0       0.40      0.40      0.40       257

    accuracy                           0.40       800
   macro avg       0.40      0.40      0.40       800
weighted avg       0.40      0.40      0.40       800



In [71]:
print('Testing Data')
print('Accuracy : ', accuracy_score(y_test, y_pred_LR2))
print('\nConfusion Matrix : \n', confusion_matrix(y_test, y_pred_LR2))
print('\nClassification Report : \n',classification_report(y_test, y_pred_LR2))

Testing Data
Accuracy :  0.345

Confusion Matrix : 
 [[15 22 19]
 [19 30 21]
 [21 29 24]]

Classification Report : 
               precision    recall  f1-score   support

         0.0       0.27      0.27      0.27        56
         1.0       0.37      0.43      0.40        70
         2.0       0.38      0.32      0.35        74

    accuracy                           0.34       200
   macro avg       0.34      0.34      0.34       200
weighted avg       0.34      0.34      0.34       200



Random Forest

In [72]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [73]:
rf1 = RandomForestClassifier(random_state=42)

In [74]:
rf1.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(random_state=42)

In [75]:
rf1.score(X_train, y_train)

0.995

In [76]:
y_pred_rf1 = rf1.predict(X_test)

In [77]:
rf1.score(X_test, y_test)

0.325

In [78]:
print('Testing Data')
print('Accuracy : ', accuracy_score(y_test, y_pred_rf1))
print('\nConfusion Matrix : \n', confusion_matrix(y_test, y_pred_rf1))
print('\nClassification Report : \n',classification_report(y_test, y_pred_rf1))

Testing Data
Accuracy :  0.325

Confusion Matrix : 
 [[20 21 15]
 [26 30 14]
 [31 28 15]]

Classification Report : 
               precision    recall  f1-score   support

         0.0       0.26      0.36      0.30        56
         1.0       0.38      0.43      0.40        70
         2.0       0.34      0.20      0.25        74

    accuracy                           0.33       200
   macro avg       0.33      0.33      0.32       200
weighted avg       0.33      0.33      0.32       200



In [79]:
print('MAE = ', mean_absolute_error(y_test, y_pred_rf1))
print('MSE = ', mean_squared_error(y_test, y_pred_rf1))
print('RMSE = ', root_mean_squared_error(y_test, y_pred_rf1))

MAE =  0.905
MSE =  1.365
RMSE =  1.1683321445547923


In [80]:
# Grid Search CV
param_grid = {
    'n_estimators': [100, 200, 300, 400, 500],
    'max_depth': [3, 5, 7, 10],
    'min_samples_leaf': [5, 10, 25, 50, 100]
}

In [81]:
rf2 = GridSearchCV(estimator=rf1, param_grid=param_grid, cv=5, verbose=1, n_jobs=-1)

In [82]:
rf2.fit(X_train, y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [3, 5, 7, 10],
                         'min_samples_leaf': [5, 10, 25, 50, 100],
                         'n_estimators': [100, 200, 300, 400, 500]},
             verbose=1)

In [83]:
#best parameters
print("Best parameters:", rf2.best_params_)
print("Best accuracy score:", rf2.best_score_)

Best parameters: {'max_depth': 10, 'min_samples_leaf': 5, 'n_estimators': 400}
Best accuracy score: 0.35124999999999995


In [84]:
# Predicted Values
rf_model = rf2.best_estimator_
y_pred_rf2 = rf_model.predict(X_test)

In [85]:
print('Testing Data')
print('Accuracy : ', accuracy_score(y_test, y_pred_rf2))
print('\nConfusion Matrix : \n', confusion_matrix(y_test, y_pred_rf2))
print('\nClassification Report : \n',classification_report(y_test, y_pred_rf2))

Testing Data
Accuracy :  0.33

Confusion Matrix : 
 [[18 25 13]
 [21 32 17]
 [31 27 16]]

Classification Report : 
               precision    recall  f1-score   support

         0.0       0.26      0.32      0.29        56
         1.0       0.38      0.46      0.42        70
         2.0       0.35      0.22      0.27        74

    accuracy                           0.33       200
   macro avg       0.33      0.33      0.32       200
weighted avg       0.33      0.33      0.32       200



In [86]:
print('MAE = ', mean_absolute_error(y_test, y_pred_rf2))
print('MSE = ', mean_squared_error(y_test, y_pred_rf2))
print('RMSE = ', root_mean_squared_error(y_test, y_pred_rf2))

MAE =  0.89
MSE =  1.33
RMSE =  1.1532562594670797


Support Vector Machine

In [87]:
from sklearn.svm import SVC

In [88]:
svc1 = SVC()

In [89]:
svc1.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [90]:
svc1.score(X_train, y_train)

0.38375

In [91]:
y_pred_svc1 = svc1.predict(X_test)

In [92]:
svc1.score(X_test, y_test)

0.325

In [93]:
print('Testing Data')
print('Accuracy : ', accuracy_score(y_test, y_pred_svc1))
print('\nConfusion Matrix : \n', confusion_matrix(y_test, y_pred_svc1))
print('\nClassification Report : \n',classification_report(y_test, y_pred_svc1))

Testing Data
Accuracy :  0.325

Confusion Matrix : 
 [[16 30 10]
 [24 34 12]
 [25 34 15]]

Classification Report : 
               precision    recall  f1-score   support

         0.0       0.25      0.29      0.26        56
         1.0       0.35      0.49      0.40        70
         2.0       0.41      0.20      0.27        74

    accuracy                           0.33       200
   macro avg       0.33      0.32      0.31       200
weighted avg       0.34      0.33      0.32       200



In [94]:
# Grid Search
param_grid_svc = {
    'C': [100, 10, 1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
}

In [95]:
svc2 = GridSearchCV(estimator=svc1, param_grid=param_grid_svc, cv=5, verbose=1, n_jobs=-1)

In [96]:
svc2.fit(X_train, y_train)

Fitting 5 folds for each of 28 candidates, totalling 140 fits


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=1)

In [97]:
#best parameters
print("Best parameters:", svc2.best_params_)
print("Best accuracy score:", svc2.best_score_)

Best parameters: {'C': 1, 'kernel': 'poly'}
Best accuracy score: 0.365


In [98]:
# Predicted Values
svc_model = svc2.best_estimator_
y_pred_svc2 = svc_model.predict(X_test)

In [99]:
print('Testing Data')
print('Accuracy : ', accuracy_score(y_test, y_pred_svc2))
print('\nConfusion Matrix : \n', confusion_matrix(y_test, y_pred_svc2))
print('\nClassification Report : \n',classification_report(y_test, y_pred_svc2))

Testing Data
Accuracy :  0.345

Confusion Matrix : 
 [[ 6 39 11]
 [11 46 13]
 [10 47 17]]

Classification Report : 
               precision    recall  f1-score   support

         0.0       0.22      0.11      0.14        56
         1.0       0.35      0.66      0.46        70
         2.0       0.41      0.23      0.30        74

    accuracy                           0.34       200
   macro avg       0.33      0.33      0.30       200
weighted avg       0.34      0.34      0.31       200



In [100]:
print('MAE = ', mean_absolute_error(y_test, y_pred_svc2))
print('MSE = ', mean_squared_error(y_test, y_pred_svc2))
print('RMSE = ', root_mean_squared_error(y_test, y_pred_svc2))

MAE =  0.76
MSE =  0.97
RMSE =  0.9848857801796105
